#!/bin/sh 

# echo "Removing previous version deployed at {{pkg.svc_data_path}}"
# rm -rf {{pkg.svc_data_path}}

# echo "Deploying new version from {{pkg.path}}/ to {{pkg.svc_data_path}}"
# cp -a {{pkg.path}}/ {{pkg.svc_data_path}}
