#!/bin/sh

echo "Conveyor expects to write its own config. Copying instead of linking."
echo "Any changes made will get reset on next init."
echo "Copying {{pkg.svc_config_path}}/conveyor.yml to {{pkg.svc_var_path}}/.conveyor"
cp -f {{pkg.svc_config_path}}/conveyor.yml {{pkg.svc_var_path}}/.conveyor
chown hab.hab {{pkg.svc_var_path}}/.conveyor